FROM php:7.2-fpm-alpine

RUN apk add curl-dev libzip-dev oniguruma-dev libxml2-dev nginx supervisor

RUN docker-php-ext-install bcmath curl json mbstring pdo pdo_mysql xml zip \
&&  docker-php-ext-enable zip curl json mbstring xml bcmath pdo pdo_mysql

RUN apk --no-cache add pcre-dev ${PHPIZE_DEPS} \
&&  pecl install redis \
&&  docker-php-ext-enable redis \
&&  apk del pcre-dev ${PHPIZE_DEPS} \
&&  rm -rf /tmp/pear

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer 

COPY docker/config/nginx.conf /etc/nginx/nginx.conf

COPY . /var/www/html
RUN composer install  --no-dev --no-interaction
RUN chmod +x /var/www/html/docker/start.sh \
&&  chmod +x /var/www/html/docker/setup.sh
RUN ln -s /var/www/html/docker/setup.sh /bin/setup-artisan

EXPOSE 80
CMD ["/var/www/html/docker/start.sh"]